feat(landing-page): redesigned footer with improved appearance, functionality, and countdown section
BirnadinErick/spc-175 pull request #146
Opened 2024-10-13 10:23 UTC by NerioNitharshan

2024-11-11 14:19 UTC, BirnadinErick requested changes

2024-11-11 14:19 UTC, BirnadinErick commented on package-lock.json
we use pnpm, please delete this

2024-11-11 14:19 UTC, BirnadinErick commented on api/v1/controllers/Projects.php
somehow this push is different from what we've seen on the meeting

2024-11-11 14:19 UTC, BirnadinErick commented on tailwind.config.cjs
please re-confirm change in these colors.

2024-11-12 10:04 UTC, NerioNitharshan commented
Okay

On Monday, 11 November 2024, Birnadin Erick ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On package-lock.json
> <https://github.com/BirnadinErick/spc-175/pull/146#discussion_r1836736476>
> :
>
> we use pnpm, please delete this
> ------------------------------
>
> On api/v1/controllers/Projects.php
> <https://github.com/BirnadinErick/spc-175/pull/146#discussion_r1836737117>
> :
>
> somehow this push is different from what we've seen on the meeting
> ------------------------------
>
> On tailwind.config.cjs
> <https://github.com/BirnadinErick/spc-175/pull/146#discussion_r1836740983>
> :
>
> please re-confirm change in these colors.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BirnadinErick/spc-175/pull/146#pullrequestreview-2427397527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANTHUCJGKRV7BPBZYFX7E2D2AC4H7AVCNFSM6AAAAABP3JQUASVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRXGM4TONJSG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-12 17:32 UTC, NerioNitharshan commented on package-lock.json
done

2024-11-12 17:33 UTC, NerioNitharshan commented on tailwind.config.cjs
no change till now

2024-11-26 15:34 UTC, closed without merging